"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function Home() {
  const router = useRouter();
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!url.trim()) return;
    setLoading(true);
    setError(null);

    try {
      const res = await fetch("/api/audit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: url.trim() }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error ?? "Something went wrong.");
        setLoading(false);
        return;
      }
      router.push(`/results/${data.id}`);
    } catch {
      setError("Network error. Please try again.");
      setLoading(false);
    }
  }

  return (
    <div className="mx-auto flex max-w-2xl flex-col items-center px-6 py-24 text-center">
      <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
        Automated SEO audits, in seconds
      </h1>
      <p className="mt-4 max-w-lg text-neutral-600 dark:text-neutral-400">
        Paste any website URL. We&apos;ll check titles, meta tags, headings, images, mobile-friendliness
        and speed — then use AI to suggest fixes and keyword ideas. No SEO knowledge required.
      </p>

      <form onSubmit={handleSubmit} className="mt-10 flex w-full max-w-lg gap-2">
        <input
          type="text"
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          placeholder="example.com"
          className="flex-1 rounded-lg border border-neutral-300 bg-white px-4 py-3 text-base outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 dark:border-neutral-700 dark:bg-neutral-900"
          disabled={loading}
        />
        <button
          type="submit"
          disabled={loading}
          className="rounded-lg bg-blue-600 px-6 py-3 font-medium text-white transition hover:bg-blue-700 disabled:opacity-50"
        >
          {loading ? "Scanning…" : "Scan"}
        </button>
      </form>

      {error && <p className="mt-4 text-sm text-red-600">{error}</p>}

      <div className="mt-16 grid grid-cols-1 gap-6 text-left sm:grid-cols-3">
        <Feature title="On-page audit" desc="Titles, meta tags, headings, alt text, structured data, and more — scored and prioritized." />
        <Feature title="AI-written fixes" desc="Get ready-to-use title, meta description, and alt text suggestions generated by AI." />
        <Feature title="Keyword ideas" desc="AI-estimated keyword and topic ideas suited to your page's actual content." />
      </div>
    </div>
  );
}

function Feature({ title, desc }: { title: string; desc: string }) {
  return (
    <div className="rounded-xl border border-neutral-200 p-5 dark:border-neutral-800">
      <h3 className="font-semibold">{title}</h3>
      <p className="mt-1 text-sm text-neutral-600 dark:text-neutral-400">{desc}</p>
    </div>
  );
}
